# Generated by Django 4.2.1 on 2023-05-21 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fecha de última modificación",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=13)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="expenses.account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="expenses.currency",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="expenses.period",
                    ),
                ),
            ],
            options={
                "verbose_name": "expenses",
                "verbose_name_plural": "expenses",
            },
        ),
        migrations.DeleteModel(
            name="Expenses",
        ),
    ]
