# Generated by Django 6.0 on 2026-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="identifier",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Identificador"),
        ),
    ]
