# Generated by Django 4.2.1 on 2023-05-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expense_delete_expenses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Gasto", "verbose_name_plural": "Gastos"},
        ),
    ]
