# Generated by Django 4.2.1 on 2023-06-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expense_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrencyConvertion",
            new_name="CurrencyConvert",
        ),
        migrations.AlterField(
            model_name="account",
            name="sign",
            field=models.IntegerField(choices=[(-1, "Debe (-)"), (1, "Haber (+)")]),
        ),
    ]
