# Generated by Django 4.2.1 on 2023-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_remove_expense_emited_expense_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
