# Generated by Django 4.2.1 on 2023-10-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0009_alter_currencyconvert_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyconvert",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
