# Generated by Django 4.2.1 on 2023-11-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0010_alter_currencyconvert_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="local_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
