# Generated by Django 4.2.1 on 2024-01-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0011_expense_local_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAsociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asociacion de cuenta",
                "verbose_name_plural": "Asociaciones de cuentas",
            },
        ),
    ]
