# Generated by Django 4.2.1 on 2024-01-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0012_bank_bankaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"verbose_name": "Banco", "verbose_name_plural": "Bancos"},
        ),
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "verbose_name": "Cuenta de banco",
                "verbose_name_plural": "Cuentas de banco",
            },
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("CREDIT", "Credito"), ("DEBIT", "Debito")],
                default="DEBIT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="description",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
