# Generated by Django 4.2.1 on 2024-01-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0012_accountasociation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="local_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=13
            ),
        ),
    ]
