# Generated by Django 4.2.1 on 2024-01-22 01:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0013_alter_expense_local_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fecha de última modificación",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Subida de archivo",
                "verbose_name_plural": "Subidas de archivos",
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="expenses.upload",
            ),
        ),
    ]
