# Generated by Django 4.2.1 on 2024-01-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0014_upload_expense_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="lines",
            field=models.IntegerField(default=0),
        ),
    ]
