# Generated by Django 4.2.1 on 2024-01-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0015_upload_lines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
