# Generated by Django 4.2.1 on 2024-01-28 22:01

from django.db import migrations, models

import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0016_alter_upload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=expenses.models.expense_upload_path
            ),
        ),
    ]
