# Generated by Django 4.2.1 on 2024-03-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0022_alter_account_account_type_alter_account_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Expense",
            new_name="Transaction",
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
            },
        ),
    ]
