# Generated by Django 4.2.1 on 2024-04-27 21:48

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0023_rename_expense_transaction_alter_transaction_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="lines",
        ),
        migrations.AddField(
            model_name="upload",
            name="dimension",
            field=models.JSONField(
                default=expenses.models.upload_dimension_default,
                verbose_name="Dimension del document",
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=expenses.models.upload_parameters_default,
                null=True,
                verbose_name="Parámetros",
            ),
        ),
    ]
