# Generated by Django 4.2.1 on 2024-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0024_remove_upload_lines_upload_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="Datos"),
        ),
    ]
