# Generated by Django 4.2.1 on 2024-06-10 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0025_upload_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=13, verbose_name="Monto"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Programado"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción programada",
                "verbose_name_plural": "Transacciones programadas",
            },
        ),
    ]
