# Generated by Django 4.2.1 on 2024-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0026_programtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="identifier",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
