# Generated by Django 4.2.1 on 2024-07-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0027_transaction_identifier"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("month", "year")},
        ),
    ]
