# Generated by Django 4.2.14 on 2024-08-04 22:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0028_alter_period_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=13, verbose_name="Monto"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=13, verbose_name="Pago mensual"
                    ),
                ),
                ("months", models.SmallIntegerField(default=0, verbose_name="Meses")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("bank", models.CharField(max_length=100, verbose_name="Banco")),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.currency",
                    ),
                ),
            ],
        ),
    ]
