# Generated by Django 4.2.14 on 2024-08-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0029_loan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"verbose_name": "Préstamo", "verbose_name_plural": "Préstamos"},
        ),
        migrations.RemoveField(
            model_name="loan",
            name="end_date",
        ),
    ]
