# Generated by Django 4.2.14 on 2024-08-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0030_alter_loan_options_remove_loan_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="expenses.currency"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("MOVIES", "Películas"),
                            ("MUSIC", "Música"),
                            ("BOOKS", "Libros"),
                        ],
                        default="MOVIES",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=13, verbose_name="Pago mensual"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expenses.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
    ]
