# Generated by Django 4.2.14 on 2024-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0031_alter_loan_currency_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("MOVIES", "Películas"),
                    ("MUSIC", "Música"),
                    ("BOOKS", "Libros"),
                    ("OTHER", "Otros"),
                ],
                default="MOVIES",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
    ]
