# Generated by Django 4.2.14 on 2025-04-17 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0033_alter_transaction_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Fecha de fin",
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Fecha de inicio",
            ),
        ),
    ]
