# Generated by Django 4.2.1 on 2024-01-15 04:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0012_accountasociation"),
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "period")},
        ),
    ]
