# Generated by Django 4.2.1 on 2024-01-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_alter_matchaccount_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetassignment",
            name="budget_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="budgetassignment",
            name="expense_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
