# Generated by Django 4.2.1 on 2024-01-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_alter_budgetassignment_budget_amount_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budgetassignment",
            unique_together={("budget", "category")},
        ),
    ]
