# Generated by Django 4.2.1 on 2024-02-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expenses",
            "0021_alter_currencyconvert_currency_alter_expense_account_and_more",
        ),
        ("budgets", "0007_alter_budgetassignment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchaccount",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="expenses.account"
            ),
        ),
        migrations.AlterField(
            model_name="matchaccount",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgets.category"
            ),
        ),
    ]
