# Generated by Django 4.2.14 on 2025-02-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0009_alter_budgetassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={
                "ordering": ["-period"],
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
            },
        ),
    ]
